---
kind: "operation"
client: "atomist 1.2"
generator:
  name: "NewRugArchiveProject"
  group: "atomist-rugs"
  artifact: "rug-archive"
  version: "0.11.0"
  origin:
    repo: "https://github.com/atomist-rugs/rug-archive.git"
    branch: "a881183f4382aa17443b589213889902d2ae69ac"
    sha: "a881183"
  parameters:
    - "project_name": "lifecycle-demo"
    - "group_id": "atomisthqa"
    - "version": "0.1.0"
    - "description": "My new project"

---
kind: "operation"
client: "atomist-bot"
executor:
  name: "EnableTravisForRugArchive"
  group: "atomist-rugs"
  artifact: "travis-editors"
  version: "0.12.2"
  origin:
    repo: "https://github.com/atomist-rugs/travis-editors.git"
    branch: "fb5fab9406ad30c0be90cb8272a8bb22fd8a3242"
    sha: "fb5fab9"
  parameters:
    - "github_token": "a**************************************8"
    - "maven_user": "t***************y"
    - "maven_token": "z**************7"
    - "owner": "atomisthq"
    - "repo": "lifecycle-demo"
    - "org": ".org"
    - "maven_base_url": "https://atomist.jfrog.io/atomist"

