dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
  - secure: JS7LQBAeqUFkga8yPQoNvgkdaGPrxvD77DTfMsV/n31gatiMwETNbynqVW/l5wQIIigkd12oy4DOnc01CbxpREknLaLal9fOjQSKItlJ8zFzYrLJ2jakgCfsWsYFfZAa7YmXU+j3dkk03yVQ6bWxfeMusHWa04qmf/Urjg1Pnb1SEhF04XDL530ZWO3hgtSqCYndP7OzreHdWH8fsuVFI8fvpNibiptsNJcLht92kHw0CeUjOcEfMrQUIvUSrBTb9VeDOaTUJbJ1dTzwpRxfmOYcAWyER5kbEae9cy0Avk3ar8WH1/85bScK3SURVuMjILcBo6GSIixwwwGJg90WkLdtBMZPB6FiocBB/AE9au1Znkujq8FWR/bzpABSie+8+XDjkIdU40H+yalDeYV4m0381k2QFOhrXIAUGUAsJuXPOVE2S0LdE3HySuFBHBGGfYlsooToi86lF+BgWJlV5ZPIv/ep0nAQ1X0giHRXVIF1PLjf5BhfWT+AxmHZlBkEipolCgY2V63nfuulbj4IpAlLCT5HTf6/0BTH7ZvhbUJspcnDoMKZM5FjXu1xcShvZlN8qmEQQLAn/y0nCPBZ6S5GALucs/PCb52Ozhmdejt7s5IOPgEbs7jPoDWosy7IloBZrDGGXz4JUvhDunirpt7eu6XgVywyOhZWaU7cFCw=
  - secure: nqmTDCa2pUYk6huevKrHNOKXeb5UOlACvCCf0lJs8vhsh++2xLcV8NXP4LSdQIsk5OLny3uLlCdVwfc4oHT2gj1v90ewSTHeZXxECd4ocucG0UtfYPB0Didsznq9XwYoekMkQAAgtTlEenJjCxvZmhSB2vCL7PthKPKNKsl2rEevbEoSrL1VWhGMvNLEoARNad5KLVNrHw9RqIEDHWnijLaJBXZyBgbWm4rJ6YwgzOBozLYxOPaFF3g5GGa46yOR/WAPhan4BPxYKYtLiU0UetWR6oAqeRZ7o9l0JcNYI1mZe9+8tTHAAJfuuFo/48DyJIsh9WCMLVc1mlnovWbVmPIgTMOxKkf3AgVlKOxBT4w/ojuVEp2BdENBG+7zx6llE6Oc9tuDkpQ4zgnryFf1OnGpkWgzNSu+KKF85IXakHreOP7GGV4SRsL+Q6/alh+kubsifW5WmLKNd1UGZD5i6Ga6NZvBWVlPvPNVYT5S1UnKJ5qFeDAEiVM5/7YIB5oKexWLv6NKyKLE6YsCs9GaXWQTvsJ/472CNUneo0wg2jby2dLgqhejPq5LYYwyeOjQjufvT5weiuAjdmeWrlnaUoqYcUviyUxwkx/U6Yxuu+f2rqsrwgorOj2oYrinuTmpHxLocmyJVy8N5OuFWiC9JvGwuHw0dZfl83Y1HarQoGs=
  - secure: Q/MOWQkPz2awTbLXop/fG45CgaSaD++5JalO3CW+cKh4lX65TCXEjwl76tIMDBclRIlL1oMsrt4Fgqvfxv2/ngVOybXJIrJQx6w6hJmNctk5Xg27vefLnRQp6LkOtKVXRN8WHb4kAe0zJ7XIgV1PcMG6BkAxaDD165Nwon9clJ+LPg+IXSnqBHI+N68tgtsMqw17PSNLtfV+Y5140eftTArgloKXssK2A0WSPR38MpVmoP87XTsKorQjCbGLceihij1AST+FEMNP036iVx3cTyrpP8s1bDRhaf0tmpqfEhJi25lDAazBC60i0zpBrmO07kXCw2QX2zfjXn2JOcC+Wfix/jCTPq0PcVReePTfEQ5kDuSsUDq3ba5WLPV7yumnhwCmF4nldDNBGPeKzJKmiDzwfnKyhpx0s8mFn7Krs7c97bf1ctad8l9KQt+qn/F2yjrsP3clTZf8AetQwVUXcQIWqZYZ/buBKbSPQeN20qPeK5ZoUmumNwK4HUKN/rebbeMcU7Olad/hJTstSG3rPc5ggYRmqFiXCGk23tHit0jW3nKDu4Zg93D4FZpPQTysYm3VPTDrH2+kSqjDPuADkVFwP658Dc8qBm/7dcsoX/sVnMTD8KdcNb01LPUEzyHB/H1RiN9h697MVwmrztYKWaL31tdmOiYZRroVLaEkW7o=
install:
- nvm install 6.9.2
script: bash .atomist/build/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - $HOME/.atomist
